name: Unit tests

on:
  push:
    branches: [ master ]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Execute tests
      run: |
        ./gradlew test
